<?php

/**
 * @file
 * Contains react_drupal_block.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Cache\UncacheableDependencyTrait;


/**
 * Implements hook_help().
 */
function react_drupal_block_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the react_drupal_block module.
    case 'help.page.react_drupal_block':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Generates Google Maps components for the PleasePrepMe website using React and react-google-map') . '</p>';
      return $output;

    default:
  }
}

function react_drupal_block_theme($existing, $type, $theme, $path) {

  return array(
    'react_drupal_block' => array(
      'variables' => array(
        'uuid' => NULL,
        'contentType' => NULL
      ),
    ),
  );
}
